"""empty message

Revision ID: 3dd92de5587f
Revises: e4bb19a6a259
Create Date: 2024-01-17 04:16:25.734940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd92de5587f'
down_revision = 'e4bb19a6a259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('mass')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('height')
        batch_op.drop_column('gender')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('gravity')
        batch_op.drop_column('terrain')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=15), autoincrement=False, nullable=False))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
